<a href="https://colab.research.google.com/github/harivign/ab_testing-ds1-for-pandas-practice/blob/main/AB_Testing_dataset_for_pandas_practice_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#python pandas practice

In [6]:
#Calculate the mean and median of Page Views and Time Spent for both groups (A and B)
#Which group has a higher conversion rate? Is the difference significant?
#Group the data by Device and calculate the average Time Spent and Page Views for each device type
#Find the total number of users and the conversion rate for each location.
#Identify users who spent more than 200 seconds on the site and viewed more than 5 pages.

In [7]:
import pandas as pd

In [8]:
df=pd.read_csv("/content/ab_testing.csv")  # copy your file path

In [9]:
df

,User ID,Group,Page Views,Time Spent,Conversion,Device,Location
0,14292,B,3,424,No,Mobile,Northern Ireland
1,11682,A,9,342,No,Mobile,Scotland
2,19825,A,2,396,No,Desktop,Northern Ireland
3,16080,B,4,318,No,Desktop,Wales
4,18851,A,1,338,Yes,Desktop,Scotland
...,...,...,...,...,...,...,...
4995,16360,B,12,313,No,Mobile,Wales
4996,18084,B,10,313,No,Desktop,Northern Ireland
4997,12063,A,11,156,No,Desktop,England
4998,18647,B,13,346,No,Desktop,Wales
4999,16686,A,11,208,No,Desktop,Northern Ireland

In [10]:
df.columns

Index(['User ID', 'Group', 'Page Views', 'Time Spent', 'Conversion', 'Device',
       'Location'],
      dtype='object')

In [11]:
#Calculate the mean and median of Page Views and Time Spent for both groups (A and B)
df["Group"].unique()

array(['B', 'A'], dtype=object)

In [12]:
grouped=df.groupby("Group")

In [13]:
data=grouped[["Page Views","Time Spent"]].agg(["mean","median"])
data

      Page Views         Time Spent
            mean median        mean median
Group
A       7.581580    8.0  241.733227  241.0
B       7.492946    8.0  243.303910  244.0

In [14]:
#Which group has a higher conversion rate? Is the difference significant?

In [17]:
total_yes=df.groupby("Group")["Conversion"].apply(lambda i: (i=="Yes").sum() )

In [18]:
total_yes

Group
A    136
B    349
Name: Conversion, dtype: int64

In [20]:
total_user=df.count()
total_user

User ID       5000
Group         5000
Page Views    5000
Time Spent    5000
Conversion    5000
Device        5000
Location      5000
dtype: int64

In [24]:
users = df['Group'].value_counts()
users

Group
A    2519
B    2481
Name: count, dtype: int64

In [26]:
conversion_rate=(total_yes/users)
conversion_rate=conversion_rate*100
conversion_rate

Group
A     5.398968
B    14.066909
dtype: float64

In [29]:
group_A=conversion_rate["A"]
group_B=conversion_rate["B"]

In [30]:
output = f"the Group A conversion rate is {group_A:.2f}% and the Group B conversion rate is {group_B:.2f}% "
print(output)

the Group A conversion rate is 5.40% and the Group B conversion rate is 14.07%

In [ ]:
#Group the data by Device and calculate the average Time Spent and Page Views for each device type

In [36]:
df.groupby("Device")

In [38]:
df.groupby("Device")[["Time Spent","Page Views"]].mean()

         Time Spent  Page Views
Device
Desktop  243.185579    7.530339
Mobile   241.818846    7.545085

In [ ]:
#Find the total number of users and the conversion rate for each location.

In [41]:
df

,User ID,Group,Page Views,Time Spent,Conversion,Device,Location
0,14292,B,3,424,No,Mobile,Northern Ireland
1,11682,A,9,342,No,Mobile,Scotland
2,19825,A,2,396,No,Desktop,Northern Ireland
3,16080,B,4,318,No,Desktop,Wales
4,18851,A,1,338,Yes,Desktop,Scotland
...,...,...,...,...,...,...,...
4995,16360,B,12,313,No,Mobile,Wales
4996,18084,B,10,313,No,Desktop,Northern Ireland
4997,12063,A,11,156,No,Desktop,England
4998,18647,B,13,346,No,Desktop,Wales
4999,16686,A,11,208,No,Desktop,Northern Ireland

In [49]:
grouped=df.groupby("Location")
grouped

In [66]:
convertion=grouped["Conversion"].apply(lambda i : (i=="Yes").sum())
convertion

Location
England             136
Northern Ireland    103
Scotland            125
Wales               121
Name: Conversion, dtype: int64

In [67]:
users_count=grouped["User ID"].count()
users_count

Location
England             1246
Northern Ireland    1242
Scotland            1281
Wales               1231
Name: User ID, dtype: int64

In [71]:
conversion_rate=(convertion/users_count)*100
conversion_rate

Location
England             10.914928
Northern Ireland     8.293076
Scotland             9.758002
Wales                9.829407
dtype: float64

In [72]:
result = pd.DataFrame({
    "Total Users": users_count,
    "Total Conversions": convertion,
    "Conversion Rate (%)": conversion_rate
})

In [73]:
print(result)

                  Total Users  Total Conversions  Conversion Rate (%)
Location
England                  1246                136            10.914928
Northern Ireland         1242                103             8.293076
Scotland                 1281                125             9.758002
Wales                    1231                121             9.829407

In [ ]:
#Identify users who spent more than 200 seconds on the site and viewed more than 5 pages.

In [83]:
 new_data=df[(df["Time Spent"] >= 200) & (df["Page Views"] >= 5)]
 new_data

,User ID,Group,Page Views,Time Spent,Conversion,Device,Location
1,11682,A,9,342,No,Mobile,Scotland
7,10041,B,9,292,No,Mobile,Northern Ireland
8,13191,B,8,434,No,Desktop,Northern Ireland
9,14427,B,12,271,No,Desktop,England
10,12776,A,14,351,No,Desktop,Wales
...,...,...,...,...,...,...,...
4994,14255,B,10,258,No,Desktop,Wales
4995,16360,B,12,313,No,Mobile,Wales
4996,18084,B,10,313,No,Desktop,Northern Ireland
4998,18647,B,13,346,No,Desktop,Wales
4999,16686,A,11,208,No,Desktop,Northern Ireland

In [85]:
 new_data["User ID"].count()

2155